create table if not exists public.postype_archive (
  id bigint generated by default as identity primary key,
  source_row_number text unique,
  postype_post_id bigint,
  title text not null,
  author text,
  published_date date,
  link text unique,
  is_paid boolean not null default false,
  is_adult boolean not null default false,
  preview text,
  category text,
  genres text,
  keywords text,
  top_tags text,
  bottom_tags text,
  endings text,
  ai_suggested_genres text,
  ai_suggested_keywords text,
  ai_suggested_top text,
  ai_suggested_bottom text,
  ai_suggested_endings text,
  summary text,
  body_extract text,
  ai_raw_response text,
  ai_confidence numeric,
  ai_processed_at text,
  cleanup_note text,
  is_series boolean not null default false,
  series_name text,
  series_volume text,
  serialization_status text,
  status_reason text,
  series_columns_unified boolean not null default false,
  series_columns_unified_note text,
  tag_limit_applied boolean not null default false,
  tag_limit_note text,
  discovered_at timestamptz default now(),
  crawled_at timestamptz,
  crawl_status text,
  crawl_error text,
  ai_status text default 'pending',
  ai_note text,
  ai_classified_at timestamptz,
  admin_reviewed boolean default false,
  admin_reviewed_at timestamptz,
  source_url text,
  deleted_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.postype_archive
  add column if not exists postype_post_id bigint,
  add column if not exists discovered_at timestamptz default now(),
  add column if not exists crawled_at timestamptz,
  add column if not exists crawl_status text,
  add column if not exists crawl_error text,
  add column if not exists ai_status text default 'pending',
  add column if not exists ai_note text,
  add column if not exists ai_classified_at timestamptz,
  add column if not exists admin_reviewed boolean default false,
  add column if not exists admin_reviewed_at timestamptz,
  add column if not exists source_url text;

do $$
begin
  if exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'postype_archive'
      and column_name = 'ai_confidence'
      and data_type <> 'numeric'
  ) then
    alter table public.postype_archive
      alter column ai_confidence type numeric
      using case
        when ai_confidence::text ~ '^\s*[0-9]+(\.[0-9]+)?\s*$' then ai_confidence::numeric
        else null
      end;
  end if;
end $$;

create index if not exists postype_archive_published_date_idx
  on public.postype_archive (published_date desc);

create index if not exists postype_archive_author_idx
  on public.postype_archive (author);

create index if not exists postype_archive_series_name_idx
  on public.postype_archive (series_name);

create unique index if not exists postype_archive_postype_post_id_uidx
  on public.postype_archive (postype_post_id)
  where postype_post_id is not null;

create unique index if not exists postype_archive_link_uidx
  on public.postype_archive (link)
  where link is not null;

create index if not exists postype_archive_ai_status_idx
  on public.postype_archive (ai_status, admin_reviewed);

create index if not exists postype_archive_discovered_at_idx
  on public.postype_archive (discovered_at desc);

create table if not exists public.postype_sources (
  id bigint generated by default as identity primary key,
  source_type text,
  source_url text unique not null,
  enabled boolean not null default true,
  last_checked_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.crawl_runs (
  id bigint generated by default as identity primary key,
  started_at timestamptz not null default now(),
  finished_at timestamptz,
  status text,
  found_count integer not null default 0,
  inserted_count integer not null default 0,
  ai_review_count integer not null default 0,
  failed_count integer not null default 0,
  error_message text,
  created_at timestamptz not null default now()
);

create index if not exists crawl_runs_started_at_idx
  on public.crawl_runs (started_at desc);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists set_postype_archive_updated_at on public.postype_archive;
create trigger set_postype_archive_updated_at
before update on public.postype_archive
for each row execute function public.set_updated_at();

drop trigger if exists set_postype_sources_updated_at on public.postype_sources;
create trigger set_postype_sources_updated_at
before update on public.postype_sources
for each row execute function public.set_updated_at();

alter table public.postype_archive enable row level security;
alter table public.postype_sources enable row level security;
alter table public.crawl_runs enable row level security;

drop policy if exists "postype_archive_public_read" on public.postype_archive;
create policy "postype_archive_public_read"
on public.postype_archive
for select
to anon
using (deleted_at is null);

drop policy if exists "crawl_runs_public_read" on public.crawl_runs;
create policy "crawl_runs_public_read"
on public.crawl_runs
for select
to anon
using (true);

-- 개인용/비공개 배포에서 관리자 편집을 바로 쓰려면 아래 정책을 켜세요.
-- 공개 사이트에서는 anon 전체 쓰기 권한이 위험하므로 Edge Function 또는 인증 정책으로 분리하는 쪽을 권장합니다.
--
-- drop policy if exists "postype_archive_anon_insert" on public.postype_archive;
-- create policy "postype_archive_anon_insert"
-- on public.postype_archive
-- for insert
-- to anon
-- with check (true);
--
-- drop policy if exists "postype_archive_anon_update" on public.postype_archive;
-- create policy "postype_archive_anon_update"
-- on public.postype_archive
-- for update
-- to anon
-- using (true)
-- with check (true);
