create table if not exists public.postype_archive (
  id bigint generated by default as identity primary key,
  source_row_number text unique,
  postype_post_id bigint,
  title text not null,
  author text,
  published_date date,
  link text unique,
  is_paid boolean not null default false,
  is_adult boolean not null default false,
  preview text,
  category text,
  genres text,
  keywords text,
  top_tags text,
  bottom_tags text,
  endings text,
  ai_suggested_genres text,
  ai_suggested_keywords text,
  ai_suggested_top text,
  ai_suggested_bottom text,
  ai_suggested_endings text,
  summary text,
  body_extract text,
  ai_raw_response text,
  ai_confidence numeric,
  ai_processed_at text,
  cleanup_note text,
  is_series boolean not null default false,
  series_name text,
  series_volume text,
  serialization_status text,
  status_reason text,
  series_columns_unified boolean not null default false,
  series_columns_unified_note text,
  tag_limit_applied boolean not null default false,
  tag_limit_note text,
  discovered_at timestamptz default now(),
  crawled_at timestamptz,
  crawl_status text,
  crawl_error text,
  ai_status text default 'pending',
  ai_note text,
  ai_classified_at timestamptz,
  admin_reviewed boolean default false,
  admin_reviewed_at timestamptz,
  source_url text,
  deleted_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.postype_archive
  add column if not exists postype_post_id bigint,
  add column if not exists discovered_at timestamptz default now(),
  add column if not exists crawled_at timestamptz,
  add column if not exists crawl_status text,
  add column if not exists crawl_error text,
  add column if not exists ai_status text default 'pending',
  add column if not exists ai_note text,
  add column if not exists ai_classified_at timestamptz,
  add column if not exists admin_reviewed boolean default false,
  add column if not exists admin_reviewed_at timestamptz,
  add column if not exists source_url text;

do $$
begin
  if exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'postype_archive'
      and column_name = 'ai_confidence'
      and data_type <> 'numeric'
  ) then
    alter table public.postype_archive
      alter column ai_confidence type numeric
      using case
        when ai_confidence::text ~ '^\s*[0-9]+(\.[0-9]+)?\s*$' then ai_confidence::numeric
        else null
      end;
  end if;
end $$;

create index if not exists postype_archive_published_date_idx
  on public.postype_archive (published_date desc);

create index if not exists postype_archive_author_idx
  on public.postype_archive (author);

create index if not exists postype_archive_series_name_idx
  on public.postype_archive (series_name);

create unique index if not exists postype_archive_postype_post_id_uidx
  on public.postype_archive (postype_post_id)
  where postype_post_id is not null;

create unique index if not exists postype_archive_link_uidx
  on public.postype_archive (link)
  where link is not null;

create index if not exists postype_archive_ai_status_idx
  on public.postype_archive (ai_status, admin_reviewed);

create index if not exists postype_archive_discovered_at_idx
  on public.postype_archive (discovered_at desc);

create table if not exists public.postype_sources (
  id bigint generated by default as identity primary key,
  source_type text,
  source_url text unique not null,
  enabled boolean not null default true,
  last_checked_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.postype_filter_config (
  group_name text primary key check (group_name in ('장르', '키워드', '공', '수')),
  options jsonb not null default '[]'::jsonb,
  updated_at timestamptz not null default now()
);

insert into public.postype_filter_config (group_name, options)
values
  ('장르', '["현대물","학원물","캠게","노란장판","리맨물","판타지","오메가버스","가이드버스","회귀물","빙의물","환생물","재회물","첫사랑물","친구연애물","혐관물","시대물","연예계물","스포츠물","군부물","조폭물","피폐물","일상물","리얼물","수인물","종교물","느와르","청게"]'::jsonb),
  ('키워드', '["계약","재회","첫사랑","짝사랑","동거","오해","구원","집착","후회","복수","비밀연애","신분차이","나이차","소꿉친구","친구에서연인","정략결혼","임신","육아","상처","질투","쌍방구원","쌍방짝사랑","혐관","배틀연애","권선징악","달달물","코믹","잔잔물","피폐","외전","궁중물","환생","학원물","사고","일상물","죽음","상실","사내연애","원나잇","기억상실","좀비아포칼립스","스폰서","네임버스","프로게이머"]'::jsonb),
  ('공', '["다정공","헌신공","강공","냉혈공","무심공","까칠공","츤데레공","능글공","초딩공","집착공","광공","개아가공","계략공","후회공","사랑꾼공","순정공","절륜공","존댓말공","대형견공","연하공","연상공","재벌공","능력공","황제공","왕자공","귀족공","군인공","배우공","아이돌공","조폭공","양아치공","인외공","상처공","동정공","헤테로공","짝사랑공"]'::jsonb),
  ('수', '["다정수","단정수","소심수","헌신수","강수","냉혈수","무심수","까칠수","츤데레수","허당수","지랄수","계략수","유혹수","적극수","잔망수","명랑수","순진수","임신수","도망수","굴림수","후회수","능글수","능력수","순정수","떡대수","평범수","연하수","연상수","재벌수","황제수","왕자수","귀족수","군인수","배우수","아이돌수","조폭수","양아치수","인외수","상처수","병약수","동정수","헤테로수","짝사랑수"]'::jsonb)
on conflict (group_name) do nothing;

create table if not exists public.crawl_runs (
  id bigint generated by default as identity primary key,
  started_at timestamptz not null default now(),
  finished_at timestamptz,
  status text,
  found_count integer not null default 0,
  inserted_count integer not null default 0,
  ai_review_count integer not null default 0,
  failed_count integer not null default 0,
  error_message text,
  created_at timestamptz not null default now()
);

create table if not exists public.postype_authors (
  id uuid primary key default gen_random_uuid(),
  display_name text not null unique,
  postype_channel_url text not null unique,
  key_hash text not null,
  enabled boolean not null default true,
  last_login_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.postype_author_submissions (
  id uuid primary key default gen_random_uuid(),
  author_id uuid not null references public.postype_authors(id) on delete cascade,
  status text not null default 'pending_review'
    check (status in ('pending_review', 'approved', 'rejected', 'withdrawn')),
  post_url text not null,
  postype_post_id bigint,
  title text not null,
  published_date date,
  category text not null default '글',
  is_paid boolean not null default false,
  is_adult boolean not null default false,
  genres text,
  keywords text,
  top_tags text,
  bottom_tags text,
  endings text,
  is_series boolean not null default false,
  series_name text,
  series_volume text,
  serialization_status text,
  review_note text,
  reviewed_at timestamptz,
  archived_post_id bigint references public.postype_archive(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.postype_author_submissions
  add column if not exists published_date date;

create index if not exists postype_author_submissions_status_idx
  on public.postype_author_submissions (status, created_at desc);

create index if not exists postype_author_submissions_author_idx
  on public.postype_author_submissions (author_id, created_at desc);

create index if not exists crawl_runs_started_at_idx
  on public.crawl_runs (started_at desc);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists set_postype_archive_updated_at on public.postype_archive;
create trigger set_postype_archive_updated_at
before update on public.postype_archive
for each row execute function public.set_updated_at();

drop trigger if exists set_postype_sources_updated_at on public.postype_sources;
create trigger set_postype_sources_updated_at
before update on public.postype_sources
for each row execute function public.set_updated_at();

drop trigger if exists set_postype_filter_config_updated_at on public.postype_filter_config;
create trigger set_postype_filter_config_updated_at
before update on public.postype_filter_config
for each row execute function public.set_updated_at();

drop trigger if exists set_postype_author_submissions_updated_at on public.postype_author_submissions;
create trigger set_postype_author_submissions_updated_at
before update on public.postype_author_submissions
for each row execute function public.set_updated_at();

drop trigger if exists set_postype_authors_updated_at on public.postype_authors;
create trigger set_postype_authors_updated_at
before update on public.postype_authors
for each row execute function public.set_updated_at();

alter table public.postype_archive enable row level security;
alter table public.postype_sources enable row level security;
alter table public.postype_filter_config enable row level security;
alter table public.crawl_runs enable row level security;
alter table public.postype_authors enable row level security;
alter table public.postype_author_submissions enable row level security;

drop policy if exists "postype_archive_public_read" on public.postype_archive;
drop policy if exists "crawl_runs_public_read" on public.crawl_runs;
drop policy if exists "postype_filter_config_public_read" on public.postype_filter_config;
create policy "postype_filter_config_public_read"
on public.postype_filter_config
for select
to anon, authenticated
using (true);

revoke all on public.postype_archive from anon, authenticated;
revoke all on public.postype_sources from anon, authenticated;
revoke all on public.postype_filter_config from anon, authenticated;
revoke all on public.crawl_runs from anon, authenticated;
revoke all on public.postype_authors from anon, authenticated;
revoke all on public.postype_author_submissions from anon, authenticated;

-- The public site reads only these non-sensitive columns. The base table remains private.
create or replace view public.postype_archive_public
with (security_barrier = true)
as
select
  id,
  source_row_number,
  title,
  author,
  published_date,
  link,
  is_paid,
  is_adult,
  category,
  genres,
  keywords,
  top_tags,
  bottom_tags,
  endings,
  is_series,
  series_name,
  series_volume,
  serialization_status,
  admin_reviewed
from public.postype_archive
where deleted_at is null;

create or replace view public.crawl_runs_public
with (security_barrier = true)
as
select
  id,
  started_at,
  finished_at,
  status,
  found_count,
  inserted_count,
  ai_review_count,
  failed_count,
  created_at
from public.crawl_runs;

revoke all on public.postype_archive_public from public;
revoke all on public.crawl_runs_public from public;
grant select on public.postype_archive_public to anon, authenticated;
grant select on public.crawl_runs_public to anon, authenticated;
grant select on public.postype_filter_config to anon, authenticated;

-- 개인용/비공개 배포에서 관리자 편집을 바로 쓰려면 아래 정책을 켜세요.
-- 공개 사이트에서는 anon 전체 쓰기 권한이 위험하므로 Edge Function 또는 인증 정책으로 분리하는 쪽을 권장합니다.
--
-- drop policy if exists "postype_archive_anon_insert" on public.postype_archive;
-- create policy "postype_archive_anon_insert"
-- on public.postype_archive
-- for insert
-- to anon
-- with check (true);
--
-- drop policy if exists "postype_archive_anon_update" on public.postype_archive;
-- create policy "postype_archive_anon_update"
-- on public.postype_archive
-- for update
-- to anon
-- using (true)
-- with check (true);
